TGP/config/routes.rb
Rails.application.routes.draw do
  get 'user/:user_entry' , to:'user#show'
  get 'home', to: 'static#home'
  get  'team' ,to: 'static#team'
  get  'contact', to: 'static#contact'

  resources :users
  resources :cities
  resources :gossips 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

TGP/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

TGP/app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

TGP/app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :gossip_tags
    has_many :tags, through: :gossip_tags
end

TGP/app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

TGP/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    belongs_to :recipient, class_name: "User"
end

TGP/app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossip_tags
    has_many :gossips, through: :gossip_tags
end

TGP/app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

TGP/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

TGP/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
    def index
      # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
      @city=City.all
    end
  
    def show
      # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
      @city=City.find(params[:id])
    end
  
    def new
      # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
       
    end
  
    def create
      # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
      # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
      # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
     
        # @gossip = Gossip.new(params[:post])
     end
  
    def edit
      # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    end
  
    def update
      # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
      # pour info, le contenu de ce formulaire sera accessible dans le hash params
      # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    end
  
    def destroy
      # Méthode qui récupère le potin concerné et le détruit en base
      # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    end
  end
  

TGP/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

    def index
      # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
      @gossips=Gossip.all
    end
  
    def show
      # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
      @gossip=Gossip.find(params[:id])
    end
  
    def new
      # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
       @gossip = Gossip.new(title: "", content: "")
    end
  
    def create
      # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
      # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
      # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
      @gossip = Gossip.new(user: User.first, title: params[:title], content: params[:content])
        # @gossip = Gossip.new(params[:post])
        if @gossip.save
          redirect_to gossips_path
        else
          render 'new'
        end
     end

    def edit
      # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    end
  
    def update
      # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
      # pour info, le contenu de ce formulaire sera accessible dans le hash params
      # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    end
  
    def destroy
      # Méthode qui récupère le potin concerné et le détruit en base
      # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    end
  end

TGP/app/controllers/static_controller.rb
class StaticController < ApplicationController
  def team
  end

  def contact
  end

  def gossip
    @gossip=Gossip.find(params[:id])
  end
end

TGP/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
    @user=User.all
  end

  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    @user=User.find(params[:id])
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
     
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
   
      # @gossip = Gossip.new(params[:post])
   end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end
end

TGP/app/helpers/application_helper.rb
module ApplicationHelper
end

TGP/app/helpers/gossips_helper.rb
module GossipsHelper
end

TGP/app/helpers/static_helper.rb
module StaticHelper
end

TGP/app/helpers/user_helper.rb
module UserHelper
end

TGP/app/views/cities/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <title>Contact</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%=gossips_path %>">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="<%=gossips_path %>">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="<%=team_path %>">Team</a>
      <a class="nav-item nav-link" href="<%=contact_path %>">Contact</a>
    </div>
  </div>
</nav>
     
     
      <h1> <%= @city.name %></h1>
      

<% User.where(city_id: @city.id).each do |user| %>
      <% Gossip.where(user_id: user.id).each do |gossip| %>
          <%= gossip.title %><br />
          <%= gossip.user.first_name %></p><br />
         
          </div>
        </div>
           <% end %>
    <% end %>

TGP/app/views/gossips/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <title>Contact</title>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%=gossips_path %>">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="<%=gossips_path %>">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="<%=team_path %>">Team</a>
      <a class="nav-item nav-link" href="<%=contact_path %>">Contact</a>
    </div>
  </div>
</nav>

<div class="container text-center">
    <h1>Home</h1>
    <a class="nav-item nav-link" href="<%= new_gossip_path%>">Créer un nouveau potin </a>
    <p>Voici la liste de tous les potins</p>

    
</div>


<div class="container ">
<% @gossips.each do |gossip| %>
  <div class="container ">
   
      <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal"><%= gossip.user.first_name %> <%= gossip.user.last_name %></h4>
          </div>
          <div class="card-body">
            
            <div class="list-unstyled mt-3 mb-4">
              <li> <%= gossip.title %></li>
            </div>
            <button type="button" class="btn btn-lg btn-block btn-dark"><%= link_to "Voir le potin", gossip_path(gossip.id) %> </button>
          </div>  
        </div>
    <%end%>

  </div>
</div>


</body>
</html>

TGP/app/views/gossips/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <title>Contact</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%=gossips_path %>">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="<%=gossips_path %>">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="<%=team_path %>">Team</a>
      <a class="nav-item nav-link" href="<%=contact_path %>">Contact</a>
    </div>
  </div>
</nav>


<%= form_tag url_for(action: 'create'), method: "post" do %>
    <%= label_tag 'Titre :' %>
    <%= text_field_tag 'title', @gossip.title %>
    <%= label_tag 'Contenu :' %>
    <%= text_area_tag 'content', @gossip.content %>
    <%= submit_tag "Créer le potin"%>
 <% end %>


</body>
</html>

TGP/app/views/gossips/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <title>Contact</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%=gossips_path %>">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="<%=gossips_path %>">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="<%=team_path %>">Team</a>
      <a class="nav-item nav-link" href="<%=contact_path %>">Contact</a>
    </div>
  </div>
</nav>

<h1>Titre : <%=@gossip.title%></h1>
<p>
<%=@gossip.content%></br>
<%=@gossip.created_at.strftime("%d of %B, %Y")%></br>
Auteur : <%=@gossip.user.first_name%><%=@gossip.user.last_name%><%= link_to " Voir l'auteur", user_path(@gossip.user.id) %></br>
Ville : <%=@gossip.user.city.name%><%= link_to " Voir la ville et ces potins", city_path(@gossip.user.city.id) %>
</p>


</body>
</html>

TGP/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TGP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

TGP/app/views/user/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <title>Contact</title>
</head>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%=home_path %>">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="<%=home_path %>">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="<%=team_path %>">Team</a>
      <a class="nav-item nav-link" href="<%=contact_path %>">Contact</a>
    </div>
  </div>
</nav>


<body>

<h1>User</h1>
<p> BIENVENUE <%=params[:user_entry]%>! Ici c'est notre super site de potins, il est chouette, non ? </p>
    

</body>
</html>

TGP/app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <title>Contact</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%=gossips_path %>">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="<%=gossips_path %>">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="<%=team_path %>">Team</a>
      <a class="nav-item nav-link" href="<%=contact_path %>">Contact</a>
    </div>
  </div>
</nav>
     
     
      <h1> <%= @user.first_name %> <%= @user.last_name %></h1>
      <p>Age :<%= @user.age %> ans</p>
      Ville : <%=@user.city.name%><%= link_to " Voir tous les potins de la ville", city_path(@user.city.id) %>

      <p>Email :<a href="mailto:<%= @user.email %>"><%= @user.email %></a></p>
      <p>Description :<%= @user.description %></p>
    
  